name: CICD Setup
description: 'Set up the CI/CD environment for code2md'

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install code2md and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[dev]"
      shell: bash